Repository teamflow6/forestory-be, pull requests merged in 2025-08, with the labels that each got.

#63 Feature/#60
  src/main/java/com/teamflow/forestory_be/article/domain/entity/Article.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/ArticlePersistenceMapper.java
  src/main/java/com/teamflow/forestory_be/article/presentation/controller/ArticleController.java
  src/main/java/com/teamflow/forestory_be/article/presentation/dto/response/CreateArticleResponse.java
  src/main/java/com/teamflow/forestory_be/image/presentation/controller/ImageController.java
Labels: fix

#65 Fix/#62
  src/main/java/com/teamflow/forestory_be/story/chapter/infrastructure/persistence/repository/ChapterJpaRepository.java
  src/main/java/com/teamflow/forestory_be/story/series/application/service/SeriesService.java
  src/main/java/com/teamflow/forestory_be/story/series/domain/entity/Series.java
  src/main/java/com/teamflow/forestory_be/story/series/domain/vo/SeriesStatus.java
  src/main/java/com/teamflow/forestory_be/story/series/presentation/dto/response/ChapterResponse.java
  src/main/java/com/teamflow/forestory_be/story/series/presentation/dto/response/ChapterWithCreatedAt.java
  src/main/java/com/teamflow/forestory_be/user/application/dto/OnboardingUserCommand.java
  src/main/java/com/teamflow/forestory_be/user/application/dto/UpdateUserCommand.java
  src/main/java/com/teamflow/forestory_be/user/application/service/UserService.java
  src/main/java/com/teamflow/forestory_be/user/domain/entity/User.java
  src/main/java/com/teamflow/forestory_be/user/domain/vo/Introduction.java
  src/main/java/com/teamflow/forestory_be/user/presentation/UserController.java
  src/main/java/com/teamflow/forestory_be/user/presentation/dto/request/UpdateProfileRequest.java
  src/main/java/com/teamflow/forestory_be/user/presentation/dto/request/UserOnboardingRequest.java
  src/main/java/com/teamflow/forestory_be/user/presentation/dto/response/UserProfileResponse.java
Labels: feature

#77 feat: 유저 연락 링크 필드 추가 및 VO 변환
  src/main/java/com/teamflow/forestory_be/article/presentation/dto/response/ArticleAuthorResponse.java
  src/main/java/com/teamflow/forestory_be/story/chapter/presentation/dto/response/AuthorResponse.java
  src/main/java/com/teamflow/forestory_be/user/application/dto/OnboardingUserCommand.java
  src/main/java/com/teamflow/forestory_be/user/application/dto/UpdateUserCommand.java
  src/main/java/com/teamflow/forestory_be/user/application/service/UserService.java
  src/main/java/com/teamflow/forestory_be/user/domain/entity/User.java
  src/main/java/com/teamflow/forestory_be/user/domain/vo/ContactUrl.java
  src/main/java/com/teamflow/forestory_be/user/domain/vo/Introduction.java
  src/main/java/com/teamflow/forestory_be/user/domain/vo/ProfileImageUrl.java
  src/main/java/com/teamflow/forestory_be/user/infrastructure/persistence/UserPersistenceMapper.java
  src/main/java/com/teamflow/forestory_be/user/infrastructure/persistence/entity/UserJpaEntity.java
  src/main/java/com/teamflow/forestory_be/user/presentation/UserController.java
  src/main/java/com/teamflow/forestory_be/user/presentation/dto/request/UpdateProfileRequest.java
  src/main/java/com/teamflow/forestory_be/user/presentation/dto/request/UserOnboardingRequest.java
  src/main/java/com/teamflow/forestory_be/user/presentation/dto/response/UserProfileResponse.java
Labels: feature, refactor

#81 Feature: 좋아요 목록 조회 및 벌크 삭제 연산 구현
  src/main/java/com/teamflow/forestory_be/article/domain/repository/ArticleRepositoryPort.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/ArticlePersistenceAdaptor.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/repository/ArticleJpaRepository.java
  src/main/java/com/teamflow/forestory_be/likes/application/dto/command/BulkDeleteLikeCommand.java
  src/main/java/com/teamflow/forestory_be/likes/application/dto/query/GetMyLikesQuery.java
  src/main/java/com/teamflow/forestory_be/likes/application/service/LikeService.java
  src/main/java/com/teamflow/forestory_be/likes/domain/entity/Likes.java
  src/main/java/com/teamflow/forestory_be/likes/domain/repository/LikeRepositoryPort.java
  src/main/java/com/teamflow/forestory_be/likes/infrastructure/persistence/LikePersistenceAdaptor.java
  src/main/java/com/teamflow/forestory_be/likes/infrastructure/persistence/LikePersistenceMapper.java
  src/main/java/com/teamflow/forestory_be/likes/infrastructure/persistence/repository/LikeJpaRepository.java
  src/main/java/com/teamflow/forestory_be/likes/presentation/controller/LikeController.java
  src/main/java/com/teamflow/forestory_be/likes/presentation/dto/request/BulkDeleteLikeRequest.java
  src/main/java/com/teamflow/forestory_be/likes/presentation/dto/request/GetLikeRequest.java
  src/main/java/com/teamflow/forestory_be/likes/presentation/dto/response/GetMyLikesResponse.java
  src/main/java/com/teamflow/forestory_be/likes/presentation/dto/response/LikeListItem.java
  src/main/java/com/teamflow/forestory_be/story/chapter/domain/repository/ChapterRepositoryPort.java
  src/main/java/com/teamflow/forestory_be/story/chapter/infrastructure/persistence/ChapterPersistenceAdaptor.java
  src/main/java/com/teamflow/forestory_be/story/chapter/infrastructure/persistence/repository/ChapterJpaRepository.java
Labels: fix, feature
