Repository teamflow6/forestory-be, pull requests merged in 2025-04, with the labels that each got.

#2 chore: 프로젝트 초기 세팅
  .editorconfig
  .gitattributes
  .github/CODEOWNERS
  .github/pull_request_template.md
  .gitignore
  build.gradle
  docker/docker-compose.yml
  docker/init.sql
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  scripts/commit-msg.sh
  settings.gradle
  src/main/java/com/teamflow/forestory_be/ForestoryBeApplication.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/main/resources/logs/console-appender.xml
  src/main/resources/logs/file/error-appender.xml
  src/main/resources/logs/file/info-appender.xml
  src/test/java/com/teamflow/forestory_be/ForestoryBeApplicationTests.java
Labels: chore

#7 feat: 레이어 컨벤션 설정 및 공용 코드 추가
  build.gradle
  gradle.properties
  src/main/java/com/teamflow/forestory_be/support/common/domain/AggregateRoot.java
  src/main/java/com/teamflow/forestory_be/support/common/domain/BaseTimeEntity.java
  src/main/java/com/teamflow/forestory_be/support/common/domain/DomainEntity.java
  src/main/java/com/teamflow/forestory_be/support/common/exception/CustomException.java
  src/main/java/com/teamflow/forestory_be/support/common/util/TsidGenerator.java
  src/main/java/com/teamflow/forestory_be/support/config/IdGeneratorConfig.java
  src/main/java/com/teamflow/forestory_be/support/config/JpaConfig.java
Labels: feature, chore

#9 feat: 사용자 기능 기본 구조 설정 및 생성, 수정, 조회 추가
  src/main/java/com/teamflow/forestory_be/user/application/dto/CreateUserCommand.java
  src/main/java/com/teamflow/forestory_be/user/application/dto/ReadUserQuery.java
  src/main/java/com/teamflow/forestory_be/user/application/dto/UpdateUserCommand.java
  src/main/java/com/teamflow/forestory_be/user/application/service/UserService.java
  src/main/java/com/teamflow/forestory_be/user/domain/entity/User.java
  src/main/java/com/teamflow/forestory_be/user/domain/exception/InvalidUserNameException.java
  src/main/java/com/teamflow/forestory_be/user/domain/exception/UserNotFoundException.java
  src/main/java/com/teamflow/forestory_be/user/domain/repository/UserRepositoryPort.java
  src/main/java/com/teamflow/forestory_be/user/domain/vo/Name.java
  src/main/java/com/teamflow/forestory_be/user/domain/vo/UserStatus.java
  src/main/java/com/teamflow/forestory_be/user/infrastructure/persistence/UserPersistenceAdapter.java
  src/main/java/com/teamflow/forestory_be/user/infrastructure/persistence/UserPersistenceMapper.java
  src/main/java/com/teamflow/forestory_be/user/infrastructure/persistence/entity/UserJpaEntity.java
  src/main/java/com/teamflow/forestory_be/user/infrastructure/persistence/repository/UserJpaRepository.java
  src/test/java/com/teamflow/forestory_be/user/domain/entity/UserTest.java
  src/test/java/com/teamflow/forestory_be/user/domain/vo/NameTest.java
Labels: feature

#12 Feature/#11
  src/main/java/com/teamflow/forestory_be/article/application/dto/CreateArticleCommand.java
  src/main/java/com/teamflow/forestory_be/article/application/service/ArticleService.java
  src/main/java/com/teamflow/forestory_be/article/domain/entity/Article.java
  src/main/java/com/teamflow/forestory_be/article/domain/exception/InvalidContentException.java
  src/main/java/com/teamflow/forestory_be/article/domain/exception/InvalidSubtitleException.java
  src/main/java/com/teamflow/forestory_be/article/domain/exception/InvalidTitleException.java
  src/main/java/com/teamflow/forestory_be/article/domain/repository/ArticleRepositoryPort.java
  src/main/java/com/teamflow/forestory_be/article/domain/vo/ArticleStatus.java
  src/main/java/com/teamflow/forestory_be/article/domain/vo/Content.java
  src/main/java/com/teamflow/forestory_be/article/domain/vo/Subtitle.java
  src/main/java/com/teamflow/forestory_be/article/domain/vo/Title.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/ArticlePersistenceAdaptor.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/ArticlePersistenceMapper.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/entity/ArticleJpaEntity.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/repository/ArticleJpaRepository.java
  src/main/java/com/teamflow/forestory_be/article/presentation/controller/ArticleController.java
  src/main/java/com/teamflow/forestory_be/article/presentation/request/CreateArticleRequest.java
  src/main/java/com/teamflow/forestory_be/article/presentation/response/CreateArticleResponse.java
  src/test/java/com/teamflow/forestory_be/article/domain/entity/ArticleTest.java
  src/test/java/com/teamflow/forestory_be/article/domain/vo/ContentTest.java
  src/test/java/com/teamflow/forestory_be/article/domain/vo/SubtitleTest.java
  src/test/java/com/teamflow/forestory_be/article/domain/vo/TitleTest.java
  src/test/java/com/teamflow/forestory_be/article/presentation/controller/ArticleControllerTest.java
Labels: feature
