Repository teamflow6/forestory-be, pull requests merged in 2025-05, with the labels that each got.

#23 feat: 전역 예외 처리 기능 추가
  src/main/java/com/teamflow/forestory_be/support/common/advice/BaseErrorCode.java
  src/main/java/com/teamflow/forestory_be/support/common/advice/BaseErrorResponse.java
  src/main/java/com/teamflow/forestory_be/support/common/advice/GlobalExceptionAdvice.java
Labels: feature

#24 feat: 공통 응답 처리 기능 추가
  src/main/java/com/teamflow/forestory_be/support/common/advice/BaseApiResponse.java
  src/main/java/com/teamflow/forestory_be/support/common/advice/GlobalApiResponseAdvice.java
Labels: feature

#20 아티클 조회 기능 추가
  src/main/java/com/teamflow/forestory_be/article/application/dto/command/CreateArticleCommand.java
  src/main/java/com/teamflow/forestory_be/article/application/dto/query/GetArticleQuery.java
  src/main/java/com/teamflow/forestory_be/article/application/service/ArticleService.java
  src/main/java/com/teamflow/forestory_be/article/domain/exception/ArticleNotFoundException.java
  src/main/java/com/teamflow/forestory_be/article/domain/repository/ArticleRepositoryPort.java
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/ArticlePersistenceAdaptor.java
  src/main/java/com/teamflow/forestory_be/article/presentation/controller/ArticleController.java
  src/main/java/com/teamflow/forestory_be/article/presentation/dto/request/CreateArticleRequest.java
  src/main/java/com/teamflow/forestory_be/article/presentation/dto/response/ArticleAuthorResponse.java
  src/main/java/com/teamflow/forestory_be/article/presentation/dto/response/CreateArticleResponse.java
  src/main/java/com/teamflow/forestory_be/article/presentation/dto/response/GetArticleResponse.java
Labels: feature

#26 chore: 배포 스크립트 추가
  .github/workflows/deploy-dev.yml
  .github/workflows/pr-ci-test.yml
  src/main/resources/application.yml
Labels: chore

#29 feat: Swagger 설정 추가
  build.gradle
  gradle.properties
  src/main/java/com/teamflow/forestory_be/auth/infrastructure/security/SecurityIgnorePath.java
  src/main/java/com/teamflow/forestory_be/support/config/SwaggerConfig.java
  src/main/java/com/teamflow/forestory_be/user/presentation/UserApi.java
  src/main/java/com/teamflow/forestory_be/user/presentation/UserController.java
  src/main/resources/application-local.yml
  src/main/resources/application.yml
Labels: feature, chore

#31 chore: .gitignore yml 파일 조건 수정
  .gitignore
  src/main/java/com/teamflow/forestory_be/auth/infrastructure/security/SecurityIgnorePath.java
  src/main/java/com/teamflow/forestory_be/support/common/presentation/HealthController.java
  src/main/resources/application-dev.yml
Labels: chore

#33 refactor: 아티클 엔티티 테이블명 추가 (#32)
  src/main/java/com/teamflow/forestory_be/article/infrastructure/persistence/entity/ArticleJpaEntity.java
Labels: refactor
